config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  devise_for :users, path: '/'
  resources :books
  resources :favorite_books, only: [:index] do
    post ':book_id', action: :create, as: :create, on: :collection
    delete ':book_id', action: :destroy, as: :destroy, on: :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  include Searchable
  validates_presence_of :title, :author, :description, :picture

  mount_uploader :picture, BookPictureUploader
  
  def self.paginate_search(params = {}) 
    direction = params[:sort] || :desc
    search(params[:search]).paginate(page: params[:page]).order(title: direction)
  end
end

app/models/concerns/searchable.rb
module Searchable
  extend ActiveSupport::Concern
  
  class_methods do
    def search(keyword)
      where("#{searchable_attrs.join('||')} like ?", "%#{sanitize_sql_like(keyword.to_s)}%")
    end
    
    def searchable_attrs
      columns_hash.map{ |attr, column| [attr, column.sql_type_metadata.type] }
                  .select { |_column, type| type == :string }
                  .map { |column, _type| column }
    end
  end
end

app/models/favorite_book.rb
class FavoriteBook < ApplicationRecord
  belongs_to :book
  belongs_to :user
  
  validates_presence_of :book, :user
  validates_uniqueness_of :book_id, scope: [:user_id]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable
  has_many :favorite_books
  has_many :books, through: :favorite_books
  
  def favorite_book?(book)
    books.include?(book)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def after_sign_in_path_for(*)
    root_path
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :load_book, only: %i[edit update destroy]
  
  def new
    @book = Book.new
  end
  
  def create
    @book = Book.new(book_params)
    @book.save!
    respond_to do |format|
      format.html { redirect_to(root_path, notice: 'Book saved!') }
      format.turbo_stream { flash.now[:notice] = 'Book saved!' }
    end
  rescue ActiveRecord::RecordInvalid
    flash.now[:alert] = 'Could not save the book'
    render(:new, status: :unprocessable_entity)
  end
  
  def edit
  end

  def update
    @book.update!(book_params)
    flash.now[:notice] = 'Book saved!'
  rescue ActiveRecord::RecordInvalid
    flash.now[:alert] = 'Could not save the book'
    render(:edit, status: :unprocessable_entity)
  end
  
  def destroy
    @book.destroy!
    flash.now[:notice] = 'Book removed!'
  end
  
  private 
  
  def book_params
    params.require(:book).permit(:description, :title, :author, :picture)
  end
  
  def load_book
    @book = Book.find(params[:id])
  end
end

app/controllers/favorite_books_controller.rb
class FavoriteBooksController < ApplicationController
  before_action :load_book, only: %i[create destroy]
  
  def create
    current_user.books << book
  end
  
  def destroy
    current_user.books.destroy(book)
  end
  
  def index
    @books = current_user.books.paginate_search(params)
  end
  
  private 
  
  attr_reader :book
  
  def load_book
    @book = Book.find(params[:book_id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  
  def index
    @books = Book.paginate_search(params)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def input_errors_for(form, field_name)
    return if form.object.errors[field_name].blank?
    content_tag(:span, class: 'helper-text red-text') do
      form.object.errors[field_name].join(',')
    end
  end
  
  def input_text(form, field_name)
    content_tag(:div, class: 'input-field') do
      concat form.text_field(field_name)
      concat form.label(field_name.capitalize, for: "#{form.object.class.to_s.downcase}_#{field_name}")
      concat input_errors_for(form, field_name)
    end
  end
  
  def input_password(form, field_name)
    content_tag(:div, class: 'input-field') do
      concat form.password_field(field_name)
      concat form.label(field_name.capitalize, for: "#{form.object.class.to_s.downcase}_#{field_name}")
      concat input_errors_for(form, field_name)
    end
  end
  
  def input_file(form, field_name)
    render('layouts/form/input_file', form: form, field_name: field_name)
  end
  
  def paginate_links(collection, options = {})
    will_paginate(collection, options.merge(renderer: paginate_custom_renderer))
  end
end

app/helpers/paginate_helper.rb
module PaginateHelper
  def paginate_custom_renderer
    Class.new(::WillPaginate::ActionView::LinkRenderer) do
      def container_attributes
        {class: "pagination"}
      end
  
      def page_number(page)
        if page == current_page
          tag(:li, tag(:a, page, href: '#!'), class: 'active teal')
        else
          tag(:li, link(page, page, rel: rel_value(page)), class: 'waves-effect')
        end
      end
  
      def previous_page
        num = @collection.current_page > 1 && @collection.current_page - 1
        previous_or_next_page(num, '<', '')
      end
  
      def next_page
        num = @collection.current_page < total_pages && @collection.current_page + 1
        previous_or_next_page(num, '>', '')
      end
  
      def previous_or_next_page(page, text, classname)
        if page
          tag(:li, link(text, page, :class => classname))
        else
          tag(:li, tag(:a, text, href: '#!'), :class => classname)
        end
      end 
    end
  end
end

app/views/books/_book_card.html.haml
.col.s12.m6.l4{ id: dom_id(book) }
  .card.grey.lighten-4
    .card-image.waves-effect.waves-block.waves-light
      = image_tag(book.picture_url, class: 'activator', height: 200)
    .card-content
      %span.card-title.activator.grey-text.text-darken-4
        = book.title
        %i.material-icons.right more_vert
      %small= book.author
    - if user_signed_in?
      .card-action
        .row
          .col.s4.l4.m4
            = link_to edit_book_path(book), data: { turbo_frame: :modal }, class: 'btn-flat black-text' do
              %i.material-icons edit
          .col.s4.l4.m4
            = link_to book_path(book), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: 'btn-flat black-text' do
              %i.material-icons delete
          .col.s4.l4.m4
            - if current_user.favorite_book?(book)
              = link_to destroy_favorite_books_path(book), data: { turbo_method: :delete }, class: 'btn-flat red-text' do
                %i.material-icons favorite
            - else
              = link_to create_favorite_books_path(book), data: { turbo_method: :post }, class: 'btn-flat black-text' do
                %i.material-icons favorite_border
    .card-reveal
      %span.card-title.grey-text.text-darken-4
        Title: #{book.title}
        %i.material-icons.right close
      %small
        Author: #{book.author}
      %p= book.description
    

app/views/books/_book_list.html.haml
= turbo_frame_tag 'book-list' do
  .row
    - books.each do |book|
      = render 'books/book_card', book: book
  = paginate_links books
  = page_entries_info books
  

app/views/books/_filter_form.html.haml
= form_tag request.path, data: { turbo_frame: 'book-list', turbo_action: :advance }, method: :get do
  .row
    .col.s6
      .input-field
        = text_field_tag :search
        %label{ for: :search } Search key
    .col.s3
      .input-field
        = select_tag :sort, options_for_select(['asc', 'desc'])
        %label Sort
    .col.s3
      .input-field= button_tag 'Filter', class: 'btn grey black-text lighten-4'
      

app/views/books/_form.html.haml
= turbo_frame_tag :modal do
  .modal.modal-fixed-footer{ data: { controller: :modal, action: 'turbo:submit-end->modal#submitEnd' } }
    = form_for(@book, class: 'col s12') do |form|
      .modal-content
        = render('layouts/flash')
        %h4= modal_title
        = input_text form, :title
        = input_text form, :author
        = input_text form, :description
        = input_file form, :picture
      .modal-footer.my-5
        .btn-flat.modal-close.waves-effect.waves-green Cancel
        = form.submit 'Save', class: 'waves-effect waves-light btn modal-close'

app/views/books/create.turbo_stream.erb
<%= turbo_stream.prepend 'flash', partial: 'layouts/flash' %>

app/views/books/destroy.turbo_stream.erb
<%= turbo_stream.remove @book %>
<%= turbo_stream.prepend 'flash', partial: 'layouts/flash' %>

app/views/books/edit.html.haml
= render 'books/form', modal_title: 'Edit Book'

app/views/books/new.html.haml
= render 'books/form', modal_title: 'New Book'
          

app/views/books/update.turbo_stream.erb
<%= turbo_stream.replace @book, partial: 'books/book_card', locals: { book: @book } %>
<%= turbo_stream.prepend 'flash', partial: 'layouts/flash' %>

app/views/favorite_books/create.turbo_stream.erb
<%= turbo_stream.replace @book, partial: 'books/book_card', locals: { book: @book } %>

app/views/favorite_books/destroy.turbo_stream.erb
<%= turbo_stream.replace @book, partial: 'books/book_card', locals: { book: @book } %>

app/views/favorite_books/index.html.haml
%h4 Favorites
= render 'books/filter_form'
= render 'books/book_list', books: @books

app/views/home/index.html.haml
%h4 Home
= render 'books/filter_form'
= render 'books/book_list', books: @books
- if user_signed_in?
  .fixed-action-btn
    = link_to(new_book_path, class: 'btn-floating btn-large waves-effect waves-light teal', 
              data: { turbo_frame: :modal }) do
      %i.material-icons add

app/views/layouts/_flash.html.erb
<div data-controller='toast' 
     data-toast-messages-value='<%= flash.map { |_type, message| message } %>'>
</div>

app/views/layouts/_navbar.html.haml
%nav
  .nav-wrapper.teal
    %a.brand-logo.left{ href: "/" } Books
    %ul.right
      %li= link_to 'Books', root_path, data: { turbo: false }
      - if user_signed_in?
        %li= link_to 'Favorites', favorite_books_path, data: { turbo: false }
        %li 
          = button_to 'sign out', destroy_user_session_path, 
                      class: 'btn-logout',
                      method: :delete, data: { turbo: false }
      - else
        %li= link_to 'Login', new_user_session_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ZygoChallenge
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css'
    = stylesheet_link_tag 'https://fonts.googleapis.com/icon?family=Material+Icons'
    = javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js'
    = javascript_importmap_tags
  %body
    = render 'layouts/navbar'
    #flash= render 'layouts/flash'
    .container
      = yield
    = turbo_frame_tag :modal

app/views/layouts/form/_input_file.html.haml
.input-field.file-field
  .btn
    %span= field_name.capitalize
    = form.file_field(field_name)
  .file-path-wrapper
    = text_field_tag :file_path, nil, class: 'file-path'
  = input_errors_for(form, field_name)
  

app/views/users/shared/_links.html.haml
- if controller_name != 'sessions'
  = link_to "Log in", new_session_path(resource_name)
  %br/
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  %br/